package com.kakuab.mapper;

import com.kakuab.pojo.Clue;

import java.util.List;

public interface ClueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_clue
     *
     * @mbggenerated Fri Jun 10 13:22:15 CST 2022
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_clue
     *
     * @mbggenerated Fri Jun 10 13:22:15 CST 2022
     */
    int insert(Clue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_clue
     *
     * @mbggenerated Fri Jun 10 13:22:15 CST 2022
     */
    int insertSelective(Clue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_clue
     *
     * @mbggenerated Fri Jun 10 13:22:15 CST 2022
     */
    Clue selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_clue
     *
     * @mbggenerated Fri Jun 10 13:22:15 CST 2022
     */
    int updateByPrimaryKeySelective(Clue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_clue
     *
     * @mbggenerated Fri Jun 10 13:22:15 CST 2022
     */
    int updateByPrimaryKey(Clue record);

    int inserClue(Clue clue);

    /**
     * 根据id查询线索详细信息
     * @param id
     * @return
     */
    Clue selectClueForDateilByid(String id);

    /**
     * 查询所有线索信息
     * @return
     */
    List<Clue> selectAllClue();

    /**
     * 根据线索id查询信息
     * @param id
     * @return
     */
    Clue selectClueByid(String id);

    /**
     * 根据id删除线索
     * @param id
     * @return
     */
    int deleteClueById(String id);
}