package com.kakuab.mapper;

import com.kakuab.pojo.FunnelVO;
import com.kakuab.pojo.Tran;

import java.util.List;

public interface TranMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_tran
     *
     * @mbggenerated Thu Jun 16 14:57:02 CST 2022
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_tran
     *
     * @mbggenerated Thu Jun 16 14:57:02 CST 2022
     */
    int insert(Tran record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_tran
     *
     * @mbggenerated Thu Jun 16 14:57:02 CST 2022
     */
    int insertSelective(Tran record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_tran
     *
     * @mbggenerated Thu Jun 16 14:57:02 CST 2022
     */
    Tran selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_tran
     *
     * @mbggenerated Thu Jun 16 14:57:02 CST 2022
     */
    int updateByPrimaryKeySelective(Tran record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_tran
     *
     * @mbggenerated Thu Jun 16 14:57:02 CST 2022
     */
    int updateByPrimaryKey(Tran record);

    /**
     * 保存创建交易的信息
     * @param tran
     * @return
     */
    int insertTran(Tran tran);

    /**
     * 查询交易的全部信息
     * @return
     */
    List<Tran> selectAllTransaction();

    /**
     * 根据交易id查询交易信息
     * @param id
     * @return
     */
    Tran selectTranById(String id);

    /**
     * 查询交易表中的各个阶段数据量
     * @return
     */
    List<FunnelVO> selectCountOfTranGroupByStage();

}